#! /bin/bash

make clean
make -C tests clean

make all
make -C tests

rm store.file

util/tfstool create store.file 2048 disk1

util/tfstool write store.file tests/halt halt
util/tfstool write store.file tests/calc calc
util/tfstool write store.file tests/exec exec
util/tfstool write store.file tests/hw hw
util/tfstool write store.file tests/threads threads
util/tfstool write store.file tests/threads_locks threads_locks
util/tfstool write store.file tests/threads_ring threads_ring
util/tfstool write store.file tests/fs_open fs_open
